%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\jwagner2\git\MotionMapper\HK_20190528_151044_side_dalotia1_DeadliomstumpRight_t1DeepCut_resnet50_ball_dalotiaMay31shuffle1_300000.csv
%
% Auto-generated by MATLAB on 09-Aug-2019 14:40:54

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["scorer", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_300000", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_1", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_2", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_3", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_4", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_5", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_6", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_7", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_8", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_9", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_10", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_11", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_12", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_13", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_14", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_15", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_16", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_17", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_18", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_19", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_20", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_21", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_22", "DeepCut_resnet50_ball_dalotiaMay31shuffle1_23"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
HK20190528151044sidedalotia1DeadliomstumpRightt1DeepCutresnet50 = readtable("C:\Users\jwagner2\git\MotionMapper\HK_20190528_151044_side_dalotia1_DeadliomstumpRight_t1DeepCut_resnet50_ball_dalotiaMay31shuffle1_300000.csv", opts);


%% Clear temporary variables
clear opts